class Config:
    # email="pavanol@abc.com"
    # password="test@123"
    email="himanshuiit@gmail.com"
    password="himanshu"
    invalid_email="pavanol123@abc.com"
    invalid_password="test@123xyz"
    product_name = "MacBook"
    product_quantity = "1"
    total_price = "$602.00"
    # total_price = "$939.99"
